version: "3.7"

services:
  application:
    build: .
    image: <project-name>/server
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    networks:
      - backend
  database:
    image: postgres:12
    environment:
      PGPASSWORD: <root-password>
      POSTGRES_DB: <database-name>
      POSTGRES_USER: root
      POSTGRES_PASSWORD: <root-password>
    volumes:
      - data-pgsql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data-pgsql:
    driver: local
