version: "3.7"

services:
  app:
    build: ./build/app
    image: clothing-store/app
    volumes:
      - ./app:/var/www/html
    networks:
      - backend
  server:
    build:
      context: ./build/server
      dockerfile: Dockerfile
    image: clothing-store/server
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
    networks:
      - backend
  db:
    build: ./build/db
    image: clothing-store/db
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: main
    ports:
      - 5432:5432
    networks:
      - backend
networks:
  backend:
    driver: bridge
